# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    paths:
      - 'raw_data/**'
      - '!raw_data/README.md'
      - 'R_scripts/Generate_reports.R'
      - 'R_scripts/Generate_warnings.R'
      - 'R_scripts/Generate_map_of_reports.R'
  pull_request:
    paths:
      - 'raw_data/**'
      - '!raw_data/README.md'
      - 'R_scripts/Generate_reports.R'
      - 'R_scripts/Generate_warnings.R'
      - 'R_scripts/Generate_map_of_reports.R'

name: data-tests

jobs:
  data-tests:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
      - name: Generate reports
        id: Generate_reports
        run: |
          source("R_scripts/Generate_reports.R")
        shell: Rscript {0}
      - name: Generate warnings
        id: Generate_warnings
        run: |
          source("R_scripts/Generate_warnings.R")
        shell: Rscript {0}
      - name: Generate map of reports
        id: Generate_map_of_reports
        run: |
          source("R_scripts/Generate_map_of_reports.R")
        shell: Rscript {0}
      - name: Commit new files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add --all
          git commit -am "add data"
          git push     
      - name: Run tests
        run: Rscript testthat.R